# Configuration for the release CI/CD pipeline.

release_notes_header = """
The **Playtest Assistant** is a powerful in-game toolset for **Portal 2**, designed to streamline the collection of structured feedback and bug reports. It directly connects your playtesters to your development team via an integrated Discord bot, providing real-time, actionable data to improve your project.

> ⚠️ **Work in Progress**  
> This is a release candidate and the project is still under active development.  
> If you encounter any bugs, issues, or have feature suggestions, please open an issue on the GitHub repository.
"""

[[targets]]
enabled = true
crate_name = "injector_d3d9_proxy"
archive_name = "d3d9_proxy.zip"
files = [
    { source = "$DLL", destination = "bin/d3d9.dll" },
    { source = "assets/survey", destination = "bin/survey" },
    { source = "LICENSE", destination = "bin/LICENSE-PLAYTEST-TOOL" },
    { source = "README.md", destination = "README.md" }
]


[[targets]]
enabled = true
crate_name = "injector_server_plugin"
archive_name = "server_plugin.zip"
files = [
    { source = "$DLL", destination = "portal2/addons/playtest_assistant.dll" },
    { source = "assets/overlay.vdf", destination = "portal2/addons/overlay.vdf" },
    { source = "assets/survey", destination = "portal2/addons/survey" },
    { source = "LICENSE", destination = "portal2/addons/LICENSE-PLAYTEST-TOOL" },
    { source = "README.md", destination = "README.md" }
]


[[targets]]
enabled = false
crate_name = "injector_client_wrapper"
archive_name = "unstable_client_wrapper.zip"
files = [
    { source = "$DLL", destination = "portal2/bin/client.dll" },
    { source = "LICENSE", destination = "LICENSE-PLAYTEST-TOOL" },
]
